### ISSUE TITLE
The use of "test_dreambooth_lora.py" and "test_text_to_image_control_lora.py"

### ISSUE THREAD

**Issue by Daisy5296** [HighCWu/ControlLoRA#5]
Hi thanks for great work! I noticed you added some new files relating to dreambooth_lora and text_to_image_control_lora. May I ask what are they used for and how to use them? Could you please provide some examples? Thanks!

**Comment by HighCWu** [comment]
Just sample images from trained models for testing, see `tasks\test_lora.py` or something like `tasks\test_*.py` about all my usages. No so many modify from the train codes.

**Comment by XinDing5** [comment]
So "train_dreambooth_lora.py" trains a model of dreambooth using lora, and "train_text_to_image_control_lora.py"  trains a model for text to image generation, is that right？Any additional control involved in them?

**Comment by HighCWu** [comment]
"train_text_to_image_control_lora.py" use my controllora method to inject control image like canny image during training. Then the trained controllora model could be used to control the spatial information of stable diffusion.
