### ISSUE TITLE
The example in the readme page seems to be bad (not as good as origin controlnet model result)

### ISSUE THREAD

**Issue by universewill** [HighCWu/ControlLoRA#8]
The example in the readme page seems to be bad (not as good as origin controlnet model result). 
Why?

**Comment by HighCWu** [comment]
it's not a controlnet model but combine the idea of controlnet. it has a small parameter weight and train with simple datasets. It is more of an idea. I have not experimented out the best model channels, layer numbers and training hyperparameters.
